### ISSUE TITLE
Add scrutinizer-ci

### ISSUE THREAD

**Issue by nicolas-bastien** [prestaconcept/Sitemap#1]
Url : https://scrutinizer-ci.com/g/prestaconcept/Sitemap

-> add .scrutinizer.yml like https://github.com/prestaconcept/PrestaCMSCoreBundle/blob/master/.scrutinizer.yml

-> update travis.yml to code coverage

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

**Comment by yann-eugone** [comment]
Done within commits : 
- f5d4a0d715ba77facb32bd8af2c87ac47321927d
- bf19e1eba1f1cca8160ca2a1faf8cd5a2362b067
- 0e1d4b33b5608f7d567eed9c3f9806b4b89dbb5b
- 59e1be3d398765718f11e991855c35c3d440a1f2
- 618bd10c528d2b614523ae27c476ce778c58b2ab
